### ISSUE TITLE
New LocalTestingTool jar is needed. 

### ISSUE THREAD

**Issue by levyitay** [privacysandbox/measurement-simulation#6]
Hi team, 
Looks like LocalTestingTool jar has a fix in the JSON writer (`LocalJsonResultFileWriter.java`) which fixes the bucket id. 
The issue is that from if we are using the new LocalTestingTool which can be download from here:
```bash
VERSION=0.12.0; curl -f -o LocalTestingTool_$VERSION.jar https://aggregation-service-published-artifacts.s3.amazonaws.com/aggregation-service/$VERSION/LocalTestingTool_$VERSION.jar
```
We will get the following exception when trying to process more than 1 event:
```
at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1134)
	at com.google.aggregate.adtech.worker.AggregationWorker.createServiceManager(AggregationWorker.java:31)
	at com.google.aggregate.adtech.worker.LocalRunner.internalMain(LocalRunner.java:55)
	at com.google.measurement.adtech.LocalAggregationRunner.runAggregator(LocalAggregationRunner.java:32)
	at com.google.measurement.adtech.ProcessBatch.processElement(ProcessBatch.java:118)
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:104)
	at io.opentelemetry.sdk.OpenTelemetrySdkBuilder.buildAndRegisterGlobal(OpenTelemetrySdkBuilder.java:85)
	at com.google.privacysandbox.otel.OtlpJsonLoggingOTelConfigurationModule.provideOtelConfig(OtlpJsonLoggingOTelConfigurationModule.java:60)
	at com.google.privacysandbox.otel.OtlpJsonLoggingOTelConfigurationModule$$FastClassByGuice$$16364919.GUICE$TRAMPOLINE(<generated>)
	at com.google.privacysandbox.otel.OtlpJsonLoggingOTelConfigurationModule$$FastClassByGuice$$16364919.apply(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1134)
	at com.google.aggregate.adtech.worker.AggregationWorker.createServiceManager(AggregationWorker.java:31)
	at com.google.aggregate.adtech.worker.LocalRunner.internalMain(LocalRunner.java:55)
	at com.google.measurement.adtech.LocalAggregationRunner.runAggregator(LocalAggregationRunner.java:32)
	at com.google.measurement.adtech.ProcessBatch.processElement(ProcessBatch.java:118)
	at com.google.measurement.adtech.ProcessBatch$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228)
	at org.apache.beam.repackaged.direct_java.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187)
	at org.apache.beam.repackaged.direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:79)
	at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:244)
	at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:54)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:165)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.Throwable
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:112)
	... 47 more
	
```

Any possible solution here?

**Comment by danghle** [comment]
Hi @levyitay, this brought to the attention of the Aggregation Service team and has been fixed internally. We will update this ticket when the fix is released.

**Comment by danghle** [comment]
Hi @levyitay, the Aggregation Service team has [released ](https://github.com/privacysandbox/aggregation-service/releases/tag/v1.0.2) the fix for this issue. As such, I'm closing this issue. Please let me know if you have any questions.
