### ISSUE TITLE
IllegalArgumentException: Can not determine a default Coder error

### ISSUE THREAD

**Issue by bmaguiraz** [privacysandbox/measurement-simulation#7]
Getting the error when run

 bazel run -- //:SimulationRunner --sourceStartDate=2022-01-15 --sourceEndDate=2022-01-16 --triggerStartDate=2022-01-15 --triggerEndDate=2022-02-06 --inputDirectory=/input_directory=/path/measurement-simulation/testdata --outputDirectory=/path/measurement-simulation/output-testdata

NFO: Build completed successfully, 20 total actions
Simulating Attribution Reporting API...
Exception in thread "main" java.lang.IllegalArgumentException: Can not determine a default Coder for a 'Create' PTransform that has no elements.  Either add elements, call Create.empty(Coder), Create.empty(TypeDescriptor), or call 'withCoder(Coder)' or 'withType(TypeDescriptor)' on the PTransform.
        at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at org.apache.beam.sdk.transforms.Create.getDefaultCreateCoder(Create.java:684)
        at org.apache.beam.sdk.transforms.Create.access$300(Create.java:110)
        at org.apache.beam.sdk.transforms.Create$Values.expand(Create.java:359)
        at org.apache.beam.sdk.transforms.Create$Values.expand(Create.java:277)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482)
        at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:44)
        at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:177)
        at com.google.measurement.DataProcessor.getAttributionSourceFiles(DataProcessor.java:157)
        at com.google.measurement.DataProcessor.buildUserToSourceMap(DataProcessor.java:92)
        at com.google.measurement.SimulationRunner.run(SimulationRunner.java:87)
        at com.google.measurement.SimulationRunner.main(SimulationRunner.java:153)

**Comment by danghle** [comment]
Hi @bmaguiraz, the `--inputDirectory` you've supplied appears to be malformed. The `/input_directory=` part seems unintentional. Also please be aware that a path prefix of `/path/` implies a directory of `path` at the root, which isn't typical. To get a working invocation you can try executing with the testdata directory provided in the repo: `{directory path to repo}/measurement-simulation/testdata`. Please let us know if you have any questions, thanks.
